{ pkgs, inputs, ... }:
let
    statusLine = pkgs.writeShellApplication {
        name = "claude-statusline";
        runtimeInputs = [ pkgs.jq pkgs.git ];
        text = ''
            input=$(cat)

            DIR=$(jq -r '.workspace.current_dir' <<<"$input")
            ADDED=$(jq -r '.cost.total_lines_added // 0' <<<"$input")
            REMOVED=$(jq -r '.cost.total_lines_removed // 0' <<<"$input")
            CTX_PCT=$(jq -r '.context_window.used_percentage // 0' <<<"$input" | cut -d. -f1)
            RATE_PCT=$(jq -r '.rate_limits.five_hour.used_percentage // 0' <<<"$input" | cut -d. -f1)
            RATE_RESETS_AT=$(jq -r '.rate_limits.five_hour.resets_at // empty' <<<"$input")

            GREEN='\033[32m'; YELLOW='\033[33m'; RED='\033[31m'; DIM='\033[2m'; RESET='\033[0m'
            WHITE='\033[97m'; BRIGHT_BLUE='\033[94m'

            # Green under 70%, yellow 70-89%, red 90%+ — used for both bar fills.
            bar_color() {
                local pct=$1
                if [ "$pct" -ge 90 ]; then printf '%s' "$RED"
                elif [ "$pct" -ge 70 ]; then printf '%s' "$YELLOW"
                else printf '%s' "$GREEN"; fi
            }

            make_bar() {
                local pct=$1 width=''${2:-10}
                local filled=$((pct * width / 100))
                local empty=$((width - filled))
                local fill="" pad=""
                [ "$filled" -gt 0 ] && printf -v fill '%*s' "$filled" ""
                [ "$empty" -gt 0 ] && printf -v pad '%*s' "$empty" ""
                printf '%s%s' "''${fill// /▓}" "''${pad// /░}"
            }

            # White below 80%, shading orange-to-red from 80% to 100%.
            rate_pct_color() {
                local pct=$1
                if [ "$pct" -lt 80 ]; then
                    printf '%s' "$WHITE"
                else
                    local t=$pct
                    [ "$t" -gt 100 ] && t=100
                    local g=$((165 - (165 * (t - 80)) / 20))
                    [ "$g" -lt 0 ] && g=0
                    printf '\033[38;2;255;%dm' "$g"
                fi
            }

            if [ -n "$RATE_RESETS_AT" ]; then
                NOW=$(date +%s)
                REMAIN=$((RATE_RESETS_AT - NOW))
                [ "$REMAIN" -lt 0 ] && REMAIN=0
                RESETS_TEXT="resets $((REMAIN / 3600))h $(((REMAIN % 3600) / 60))m"
            else
                RESETS_TEXT="time to code"
            fi

            DIR_DISPLAY=$DIR
            case "$DIR" in
                "$HOME"/*) DIR_DISPLAY="~''${DIR#"$HOME"}" ;;
                "$HOME") DIR_DISPLAY="~" ;;
            esac

            BRANCH=""
            if git -C "$DIR" rev-parse --git-dir >/dev/null 2>&1; then
                BRANCH=$(git -C "$DIR" branch --show-current 2>/dev/null)
            fi

            LINE="''${WHITE}[''${RESET}$(bar_color "$RATE_PCT")$(make_bar "$RATE_PCT")''${RESET}''${WHITE}]''${RESET} $(rate_pct_color "$RATE_PCT")''${RATE_PCT}%''${RESET} ''${WHITE}-''${RESET} ''${WHITE}''${RESETS_TEXT}''${RESET}"
            LINE="$LINE ''${DIM}|''${RESET} $(bar_color "$CTX_PCT")$(make_bar "$CTX_PCT" 12)''${RESET} ''${CTX_PCT}%"
            LINE="$LINE ''${DIM}|''${RESET} ''${YELLOW}''${DIR_DISPLAY}''${RESET}"
            [ -n "$BRANCH" ] && LINE="$LINE ''${BRIGHT_BLUE}($BRANCH)''${RESET}"
            LINE="$LINE ''${DIM}|''${RESET} ''${GREEN}+''${ADDED}''${RESET}/''${RED}-''${REMOVED}''${RESET}"

            echo -e "$LINE"
        '';
    };
in
{
    programs.vscode.profiles.default = {
        extensions = with pkgs.vscode-extensions; [ anthropic.claude-code ];
    };

    programs.claude-code = {
        enable = true;

        settings = {
            model = "sonnet";
            theme = "dark";
            effortLevel = "high";
            includeCoAuthoredBy = false;
            awaySummaryEnabled = false;
            agentPushNotifEnabled = true;

            permissions = {
                defaultMode = "auto";
            };

            statusLine = {
                type = "command";
                command = "${statusLine}/bin/claude-statusline";
                padding = 0;
            };
        };

        # The home-manager release pinned by this flake predates named
        # (attrsOf) plugins, so this falls back to the legacy `--plugin-dir`
        # list form instead of `plugins.caveman = ...`.
        plugins = [ inputs.caveman ];

        context = ''
            # Environment

            - OS: NixOS (host `miniature`), configured declaratively via a flake at `~/.dotfiles`.
            - This Claude Code config (`~/.claude/settings.json`, `CLAUDE.md`, agents/commands/skills) is generated by `modules/home/cli/claude.nix` via `programs.claude-code`. Prefer editing that file over editing the generated files directly, since direct edits are overwritten on the next rebuild.
        '';
    };
}
