{ pkgs, inputs, ... }:
let
  statusLine = pkgs.writeShellApplication {
    name = "claude-statusline";
    runtimeInputs = [
      pkgs.jq
      pkgs.git
    ];
    text = builtins.readFile ./statusline.sh;
  };
in
{
  programs.vscode.profiles.default = {
    extensions = with pkgs.vscode-extensions; [ anthropic.claude-code ];
  };

  programs.claude-code = {
    enable = true;

    settings = {
      model = "sonnet";
      theme = "dark";
      effortLevel = "high";
      includeCoAuthoredBy = false;
      awaySummaryEnabled = false;
      agentPushNotifEnabled = true;

      permissions = {
        defaultMode = "auto";
      };

      statusLine = {
        type = "command";
        command = "${statusLine}/bin/claude-statusline";
        padding = 0;
        refreshInterval = 30;
      };
    };

    # The home-manager release pinned by this flake predates named
    # (attrsOf) plugins, so this falls back to the legacy `--plugin-dir`
    # list form instead of `plugins.caveman = ...`.
    plugins = [ inputs.caveman ];

    skills = {
      security-audit = "${inputs.security-audit-skill}/skills/security-audit";
      ascii-art = "${inputs.ascii-art}";
    };

    agents.race-hunter = ./agents/race-hunter.md;

    context = ''
      # Environment

      - OS: NixOS (host `miniature`), configured declaratively via a flake at `~/.dotfiles`.
      - This Claude Code config (`~/.claude/settings.json`, `CLAUDE.md`, agents/commands/skills) is generated by `modules/home/cli/claude/` via `programs.claude-code`. Prefer editing that directory over editing the generated files directly, since direct edits are overwritten on the next rebuild.

      # Commit messages

      - One short lowercase line in the imperative: `add github auth`, `fix reconnects`, `remove unused code`.
      - Join several changes with `&` or commas: `fixes & PWA autoupdate`, `add github auth, remove unused code, fix cors spam`.
      - Reference issues inline as `fix #48` or `add #27`.
      - No Conventional Commits prefixes, no trailing period, no body unless a change needs explaining (e.g. benchmark numbers).
    '';
  };
}
